title: Sense HAT puzzle box
hero_image: images/banner.png
description: Use the Sense HAT and Python to hide secret information
original_url: https://raspberrypi.org/learning/sense-hat-puzzle-box
theme: red
duration: 3
listed: true
ingredient: false
copyedit: true
curriculum: 3, design-0, programming-3, phys-comp-2, manufacture-0, community-0
interests: games
technologies: raspberry-pi, electronic-components, python, sense-hat
site_areas: projects
hardware: raspberry-pi, electronic-components, sense-hat
software: python
version: 4
last_tested: 2017-01-01
steps: 
- title: Introduction
- title: What you will need
- title: Connect to the Sense HAT
- title: Set up the structure
- title: Locked or not?
- title: Temperature lock
- title: Choose a target temperature
- title: Display a clue
- title: Check for unlock
- title: "Challenge: humidity lock"
- title: Combination lock
- title: Convert orientation to an angle
- title: Set the combination
- title: Check the combination
- title: Location lock
- title: Set the target
- title: Are we nearly there yet?
- title: Arriving at the location
- title: "Challenge: more locks"
